export const ERROR_CODES = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    FAILED_TO_CREATE_TASK: 'FAILED_TO_CREATE_TASK',
    FAILED_TO_ASSIGN_TASK: 'FAILED_TO_ASSIGN_TASK',
    FAILED_TO_ADD_COMMENT: 'FAILED_TO_ADD_COMMENT'
};